stages:
  - backend
  - frontend

tox:
  stage: backend
  script:
    - pip install tox
    - cd backend
    - tox

deploy-backend:
  stage: backend
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - apt-get update && apt-get install -y sshpass
    - export DECODED_PASSWORD=$(echo $ENCODED_PASSWORD | base64 --decode)
    - sshpass -p $DECODED_PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./backend/main.py vm-user@SDmay25-20.ece.iastate.edu:~
    - sshpass -p $DECODED_PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./backend/requirements.txt vm-user@SDmay25-20.ece.iastate.edu:~/backend_requirements.txt
    - sshpass -p $DECODED_PASSWORD ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vm-user@SDmay25-20.ece.iastate.edu "pip install -r backend_requirements.txt && fuser -k 8000/tcp || true && fastapi run main.py & while ! nc -z localhost 8000; do sleep 1; done"




eslint:
  stage: frontend
  image: node:latest
  before_script:
    - cd senior-design
    - npm install
  script:
    - npx eslint .

