stages:
  - backend
  - frontend

tox:
  stage: backend
  script:
    - pip install tox
    - cd backend
    - tox

deploy-backend:
  stage: backend
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "main"'
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl bash openssh sshpass gzip
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh get-docker.sh
    - dockerd &
    - sleep 5
  script:
    - apt-get update && apt-get install -y sshpass
    - cd backend
    - docker build -t hadesbackend .
    - docker save hadesbackend | gzip > hadesbackend.tar.gz
    - export DECODED_PASSWORD=$(echo $ENCODED_PASSWORD | base64 --decode)
    - sshpass -p $DECODED_PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null hadesbackend.tar.gz vm-user@SDmay25-20.ece.iastate.edu:/tmp/
    - sshpass -p $DECODED_PASSWORD ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vm-user@SDmay25-20.ece.iastate.edu "ddocker load < /tmp/hadesbackend.tar.gz && docker container stop hadescontainer || true && docker rm hadescontainer || true && docker run -d --name hadescontainer -p 8000:8000 hadesbackend"


eslint:
  stage: frontend
  image: node:latest
  before_script:
    - cd senior-design
    - npm install
  script:
    - npx eslint .

