stages:
  - tox
  - lint

backend:
  stage: tox
  script:
    - pip install tox
    - cd backend
    - tox

eslint:
  stage: lint
  image: node:latest
  before_script:
    - npm install
  script:
    - npx eslint .

