stages:
  - tox
  - lint
  - coverage

backend:
  stage: tox
  script:
    - pip install tox
    - cd backend
    - tox

eslint:
  stage: lint
  image: node:latest
  before_script:
    - cd senior-design
    - npm install
  script:
    - npx eslint .

coverage:
  stage: coverage
  image: node:latest
  before_script:
    - cd senior-design
    - npm install
  script:
    - npx vitest run --coverage

